"use client";

import React, { useEffect } from "react";
import { X, AlertTriangle, Info } from "lucide-react";

interface SupplierScoreDetails {
  supplierId: string;
  supplierName: string;
  supplierLogo: string;
  category: string;
  score: string;
  explanation: string;
  standoutPoints: string[];
  allSupplierComparisons: {
    name: string;
    score: string;
    description: string;
    isSelected?: boolean;
  }[];
}

interface SidebarProps {
  isOpen: boolean;
  onClose: () => void;
  supplierDetails: SupplierScoreDetails | null;
}

const SupplierScoringSidebar: React.FC<SidebarProps> = ({ 
  isOpen, 
  onClose, 
  supplierDetails 
}) => {
  // Handle escape key to close sidebar
  useEffect(() => {
    const handleEscape = (event: KeyboardEvent) => {
      if (event.key === 'Escape' && isOpen) {
        onClose();
      }
    };

    if (isOpen) {
      document.addEventListener('keydown', handleEscape);
      // Prevent body scroll when sidebar is open
      document.body.style.overflow = 'hidden';
    }

    return () => {
      document.removeEventListener('keydown', handleEscape);
      document.body.style.overflow = 'unset';
    };
  }, [isOpen, onClose]);

  if (!supplierDetails) return null;

  return (
    <>
      {/* Backdrop overlay */}
      {isOpen && (
        <div 
          className="fixed inset-0 bg-black bg-opacity-50 z-40"
          onClick={onClose}
        />
      )}
      
      {/* Sidebar */}
      <div className={`
        fixed right-0 w-[515px] bg-white shadow-lg z-50
        transform transition-transform duration-300 ease-in-out flex flex-col
        ${isOpen ? 'translate-x-0' : 'translate-x-full'}
      `} style={{ height: 'calc(100vh - 102px)', top: '90px', marginTop: 0, paddingTop: 0 }}>
        {/* Header Section */}
        <div className="flex items-center justify-between p-6 border-b border-[var(--border-light)] flex-shrink-0">
          <h2 className="text-[18px] font-bold text-[#1e2832]">
            {supplierDetails.category}
          </h2>
          <button 
            className="w-6 h-6 flex items-center justify-center hover:bg-gray-100 rounded"
            onClick={onClose}
            aria-label="Close sidebar"
          >
            <X size={20} className="text-[var(--text-secondary)]" />
          </button>
        </div>

        {/* Scrollable Content Section */}
        <div className="flex-1 overflow-y-auto" style={{ maxHeight: 'calc(100vh - 102px - 80px)' }}>
          <div className="p-6 space-y-6">
            {/* Supplier Info Card */}
            <div className="bg-[#f9fafb] border border-[#f3f4f6] rounded-lg p-6">
              <div className="space-y-6">
                {/* Supplier Logo */}
                <img 
                  src={supplierDetails.supplierLogo} 
                  alt={supplierDetails.supplierName} 
                  className="w-[85px] h-[85px] object-cover rounded"
                  onError={(e) => {
                    // Fallback to a placeholder if image fails
                    (e.currentTarget as HTMLImageElement).src = "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iODUiIGhlaWdodD0iODUiIHZpZXdCb3g9IjAgMCA4NSA4NSIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KICA8cmVjdCB3aWR0aD0iODUiIGhlaWdodD0iODUiIHJ4PSI4IiBmaWxsPSIjRjVGN0ZCIi8+CiAgPHRleHQgeD0iNDIuNSIgeT0iNTMiIGZvbnQtZmFtaWx5PSJzeXN0ZW0tdWksIC1hcHBsZS1zeXN0ZW0sICdTZWdvZSBVSScsIFJvYm90bywgJ0hlbHZldGljYSBOZXVlJywgQXJpYWwiIGZvbnQtc2l6ZT0iMTQiIGZvbnQtd2VpZ2h0PSI2MDAiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGZpbGw9IiM5Q0EzQUYiPkE8L3RleHQ+Cjwvc3ZnPgo=";
                  }}
                />
                
                {/* Score Explanation */}
                <h3 className="text-[14px] font-bold text-[#1e2832]">
                  Why this has scored {supplierDetails.score}
                </h3>
                
                {/* Detailed Description */}
                <p className="text-[14px] text-[#4d5761] leading-tight">
                  {supplierDetails.explanation}
                </p>
                
                {/* What Stood Out */}
                <div className="space-y-3">
                  <p className="text-[14px] text-[#4d5761] font-medium">What stood out for us</p>
                  <ul className="space-y-1 ml-5">
                    {supplierDetails.standoutPoints.map((point, index) => (
                      <li key={index} className="list-disc text-[14px] text-[#4d5761] leading-tight">
                        {point}
                      </li>
                    ))}
                  </ul>
                </div>
              </div>
              
              {/* AI Disclaimer */}
              <p className="text-[12px] text-[#4d5761] pt-4 border-t border-[#f3f4f6] leading-tight">
                This information has been generated by our AI-driven ranking engine, 
                and we are happy to provide more detail into the thoughts if needed.
              </p>
            </div>

            {/* Warning Section */}
            <div className="bg-[#fdeee9] border border-[#fbddd2] rounded-lg p-5">
              <div className="flex items-center gap-3 mb-3">
                <AlertTriangle size={20} className="text-[#e9571f]" />
                <h4 className="text-[14px] font-bold text-[#e9571f]">
                  What you might want to consider
                </h4>
              </div>
              <p className="text-[14px] text-[#4d5761] leading-tight">
                We only ask for 4 pricing items, so it's important you understand that 
                different installers break their prices down differently. These breakdowns 
                are to illustrate how they have reached their price and are not directly comparable.
              </p>
            </div>

            {/* Score Results Table */}
            <div>
              <h3 className="text-[14px] font-bold text-[#1e2832] mb-4">Score results</h3>
              
              <div className="space-y-0 border border-[#d3d7dc] rounded-lg overflow-hidden">
                {supplierDetails.allSupplierComparisons.map((supplier, index) => (
                  <div key={index} className="flex items-center py-4 px-4 border-b border-[#d3d7dc] last:border-b-0">
                    <div className="w-[138px] text-[14px] text-[#1e2832] leading-tight">
                      {supplier.name}
                    </div>
                    <div className="w-[99px] text-[14px] font-bold text-[#1e2832] ml-8 leading-tight">
                      {supplier.score}
                    </div>
                    <div className="flex-1 text-[14px] text-[#1e2832] leading-tight">
                      {supplier.description}
                    </div>
                  </div>
                ))}
              </div>
            </div>

            {/* Info Section */}
            <div className="bg-[#e8f1f8] border border-[#d2e3f2] rounded-lg p-5">
              <div className="flex items-center gap-3 mb-3">
                <Info size={20} className="text-[#004b75]" />
                <h4 className="text-[14px] font-bold text-[#004b75]">
                  How did we get this scoring?
                </h4>
              </div>
              <p className="text-[14px] text-[#4d5761] leading-tight">
                We use our AI-driven ranking engine to analyse bids and identify key points 
                where they differentiate from others. Our ranking favours installers who 
                detail their bids clearly.
              </p>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default SupplierScoringSidebar;
